/*
 * MyToolsContextMenu — COM DLL implementing IExplorerCommand for the Windows 11
 * modern context menu. A single parent "My Tools" command exposes a submenu
 * (EnumSubCommands) listing every tool; each child launches its PowerShell script.
 *
 * config.h is auto-generated by Register-Win11Menu.ps1 and defines TOOL_COUNT,
 * PARENT_CLSID, and the g_toolConfigs array.
 */
#include <windows.h>
#include <shobjidl.h>
#include <shlwapi.h>
#include <strsafe.h>
#include <stdio.h>
#include "config.h"

#pragma comment(lib, "shlwapi.lib")
#pragma comment(lib, "ole32.lib")

static LONG g_dllRef = 0;

// ── Debug logging to %TEMP%\mytools_contextmenu.log ──────────────────────
static void LogMsg(const char* fmt, ...)
{
    static CRITICAL_SECTION cs;
    static bool init = false;
    if (!init) { InitializeCriticalSection(&cs); init = true; }

    EnterCriticalSection(&cs);
    WCHAR path[MAX_PATH];
    GetTempPathW(MAX_PATH, path);
    StringCchCatW(path, MAX_PATH, L"mytools_contextmenu.log");

    HANDLE h = CreateFileW(path, FILE_APPEND_DATA, FILE_SHARE_READ,
                           NULL, OPEN_ALWAYS, FILE_ATTRIBUTE_NORMAL, NULL);
    if (h != INVALID_HANDLE_VALUE) {
        SYSTEMTIME st;
        GetLocalTime(&st);
        char buf[2048];
        int hdr = _snprintf_s(buf, sizeof(buf), _TRUNCATE,
            "[%04d-%02d-%02d %02d:%02d:%02d.%03d] [pid=%u] ",
            st.wYear, st.wMonth, st.wDay, st.wHour, st.wMinute, st.wSecond,
            st.wMilliseconds, GetCurrentProcessId());
        va_list args;
        va_start(args, fmt);
        int body = vsnprintf(buf + hdr, sizeof(buf) - hdr, fmt, args);
        va_end(args);
        if (body < 0) body = 0;
        buf[hdr + body] = '\n';
        DWORD written;
        WriteFile(h, buf, (DWORD)(hdr + body + 1), &written, NULL);
        CloseHandle(h);
    }
    LeaveCriticalSection(&cs);
}

static void LogGuid(const char* label, REFCLSID rclsid)
{
    WCHAR guidStr[64];
    StringFromGUID2(rclsid, guidStr, 64);
    char mb[128];
    WideCharToMultiByte(CP_UTF8, 0, guidStr, -1, mb, sizeof(mb), NULL, NULL);
    LogMsg("%s: %s", label, mb);
}

// ── Child command: one tool ──────────────────────────────────────────────
class CChildCommand : public IExplorerCommand
{
    LONG  m_ref;
    const ToolConfig* m_cfg;

public:
    CChildCommand(const ToolConfig* cfg) : m_ref(1), m_cfg(cfg)
    {
        char mb[256];
        WideCharToMultiByte(CP_UTF8, 0, cfg->title, -1, mb, sizeof(mb), NULL, NULL);
        LogMsg("CChildCommand created: %s", mb);
    }
    ~CChildCommand() { LogMsg("CChildCommand destroyed"); }

    IFACEMETHODIMP QueryInterface(REFIID riid, void** ppv)
    {
        if (!ppv) return E_POINTER;
        *ppv = NULL;
        if (IsEqualIID(riid, IID_IUnknown) || IsEqualIID(riid, IID_IExplorerCommand))
            *ppv = static_cast<IExplorerCommand*>(this);
        else
            return E_NOINTERFACE;
        AddRef();
        return S_OK;
    }
    IFACEMETHODIMP_(ULONG) AddRef()  { return InterlockedIncrement(&m_ref); }
    IFACEMETHODIMP_(ULONG) Release()
    {
        LONG c = InterlockedDecrement(&m_ref);
        if (c == 0) delete this;
        return c;
    }

    IFACEMETHODIMP GetTitle(IShellItemArray*, LPWSTR* ppszName)
    {
        if (!ppszName) return E_POINTER;
        return SHStrDupW(m_cfg->title, ppszName);
    }

    IFACEMETHODIMP GetCanonicalName(GUID* pguid)
    {
        if (!pguid) return E_POINTER;
        *pguid = m_cfg->clsid;
        return S_OK;
    }

    IFACEMETHODIMP GetIcon(IShellItemArray*, LPWSTR* ppszIcon)
    {
        if (ppszIcon) *ppszIcon = NULL;
        return S_OK;
    }

    IFACEMETHODIMP GetToolTip(IShellItemArray*, LPWSTR* ppszInfotip)
    {
        if (ppszInfotip) *ppszInfotip = NULL;
        return S_OK;
    }

    IFACEMETHODIMP GetState(IShellItemArray*, BOOL, EXPCMDSTATE* pCmdState)
    {
        if (!pCmdState) return E_POINTER;
        *pCmdState = ECS_ENABLED;
        return S_OK;
    }

    IFACEMETHODIMP Invoke(IShellItemArray* psiItemArray, IBindCtx*)
    {
        LogMsg("Invoke called");
        if (!psiItemArray) { LogMsg("Invoke: psiItemArray is NULL"); return E_INVALIDARG; }

        IShellItem* psi = NULL;
        HRESULT hr = psiItemArray->GetItemAt(0, &psi);
        if (FAILED(hr) || !psi) return E_FAIL;

        LPWSTR path = NULL;
        hr = psi->GetDisplayName(SIGDN_FILESYSPATH, &path);
        psi->Release();
        if (FAILED(hr) || !path) return E_FAIL;

        char mbPath[MAX_PATH];
        WideCharToMultiByte(CP_UTF8, 0, path, -1, mbPath, sizeof(mbPath), NULL, NULL);
        LogMsg("Invoke: path=%s", mbPath);

        WCHAR cmd[8192];
        StringCchCopyW(cmd, ARRAYSIZE(cmd), L"powershell.exe -NoProfile -ExecutionPolicy Bypass -File \"");
        StringCchCatW(cmd, ARRAYSIZE(cmd), m_cfg->scriptPath);
        StringCchCatW(cmd, ARRAYSIZE(cmd), L"\"");
        if (m_cfg->extraArgs[0]) {
            StringCchCatW(cmd, ARRAYSIZE(cmd), L" -ExtraArgs \"");
            StringCchCatW(cmd, ARRAYSIZE(cmd), m_cfg->extraArgs);
            StringCchCatW(cmd, ARRAYSIZE(cmd), L"\"");
        }
        StringCchCatW(cmd, ARRAYSIZE(cmd), L" \"");
        StringCchCatW(cmd, ARRAYSIZE(cmd), path);
        StringCchCatW(cmd, ARRAYSIZE(cmd), L"\"");
        CoTaskMemFree(path);

        char mbCmd[8192];
        WideCharToMultiByte(CP_UTF8, 0, cmd, -1, mbCmd, sizeof(mbCmd), NULL, NULL);
        LogMsg("Invoke: command=%s", mbCmd);

        STARTUPINFOW si = {0};
        si.cb = sizeof(si);
        PROCESS_INFORMATION pi = {0};
        BOOL ok = CreateProcessW(NULL, cmd, NULL, NULL, FALSE,
                                 CREATE_NO_WINDOW, NULL, NULL, &si, &pi);
        LogMsg("Invoke: CreateProcess ok=%d err=%lu", ok, GetLastError());
        if (ok) {
            CloseHandle(pi.hThread);
            CloseHandle(pi.hProcess);
        }
        return ok ? S_OK : E_FAIL;
    }

    IFACEMETHODIMP GetFlags(EXPCMDFLAGS* pFlags)
    {
        if (!pFlags) return E_POINTER;
        *pFlags = ECF_DEFAULT;
        return S_OK;
    }

    IFACEMETHODIMP EnumSubCommands(IEnumExplorerCommand** ppEnum)
    {
        if (ppEnum) *ppEnum = NULL;
        return E_NOTIMPL;
    }
};

// ── Sub-command enumerator ───────────────────────────────────────────────
class CEnumCommands : public IEnumExplorerCommand
{
    LONG m_ref;
    ULONG m_index;

public:
    CEnumCommands() : m_ref(1), m_index(0) { LogMsg("CEnumCommands created"); }
    ~CEnumCommands() { LogMsg("CEnumCommands destroyed"); }

    IFACEMETHODIMP QueryInterface(REFIID riid, void** ppv)
    {
        if (!ppv) return E_POINTER;
        *ppv = NULL;
        if (IsEqualIID(riid, IID_IUnknown) || IsEqualIID(riid, IID_IEnumExplorerCommand))
            *ppv = static_cast<IEnumExplorerCommand*>(this);
        else
            return E_NOINTERFACE;
        AddRef();
        return S_OK;
    }
    IFACEMETHODIMP_(ULONG) AddRef()  { return InterlockedIncrement(&m_ref); }
    IFACEMETHODIMP_(ULONG) Release()
    {
        LONG c = InterlockedDecrement(&m_ref);
        if (c == 0) delete this;
        return c;
    }

    IFACEMETHODIMP Next(ULONG celt, IExplorerCommand** pUICommand, ULONG* pceltFetched)
    {
        if (pceltFetched) *pceltFetched = 0;
        ULONG fetched = 0;
        for (ULONG i = 0; i < celt && m_index < (ULONG)TOOL_COUNT; i++) {
            CChildCommand* child = new CChildCommand(&g_toolConfigs[m_index]);
            if (!child) return E_OUTOFMEMORY;
            child->QueryInterface(IID_PPV_ARGS(&pUICommand[fetched]));
            child->Release();
            m_index++;
            fetched++;
        }
        if (pceltFetched) *pceltFetched = fetched;
        return (fetched == celt) ? S_OK : S_FALSE;
    }

    IFACEMETHODIMP Skip(ULONG celt)
    {
        m_index += celt;
        if (m_index > (ULONG)TOOL_COUNT) m_index = TOOL_COUNT;
        return S_OK;
    }

    IFACEMETHODIMP Reset()
    {
        m_index = 0;
        return S_OK;
    }

    IFACEMETHODIMP Clone(IEnumExplorerCommand** ppenum)
    {
        if (ppenum) *ppenum = NULL;
        return E_NOTIMPL;
    }
};

// ── Parent command: "My Tools" with submenu ──────────────────────────────
class CParentCommand : public IExplorerCommand
{
    LONG m_ref;

public:
    CParentCommand() : m_ref(1) { LogMsg("CParentCommand created"); }
    ~CParentCommand() { LogMsg("CParentCommand destroyed"); }

    IFACEMETHODIMP QueryInterface(REFIID riid, void** ppv)
    {
        if (!ppv) return E_POINTER;
        *ppv = NULL;
        if (IsEqualIID(riid, IID_IUnknown) || IsEqualIID(riid, IID_IExplorerCommand))
            *ppv = static_cast<IExplorerCommand*>(this);
        else
            return E_NOINTERFACE;
        AddRef();
        return S_OK;
    }
    IFACEMETHODIMP_(ULONG) AddRef()  { return InterlockedIncrement(&m_ref); }
    IFACEMETHODIMP_(ULONG) Release()
    {
        LONG c = InterlockedDecrement(&m_ref);
        if (c == 0) delete this;
        return c;
    }

    IFACEMETHODIMP GetTitle(IShellItemArray*, LPWSTR* ppszName)
    {
        if (!ppszName) return E_POINTER;
        LogMsg("Parent GetTitle -> My Tools");
        return SHStrDupW(L"My Tools", ppszName);
    }

    IFACEMETHODIMP GetCanonicalName(GUID* pguid)
    {
        if (!pguid) return E_POINTER;
        *pguid = PARENT_CLSID;
        return S_OK;
    }

    IFACEMETHODIMP GetIcon(IShellItemArray*, LPWSTR* ppszIcon)
    {
        if (ppszIcon) *ppszIcon = NULL;
        return S_OK;
    }

    IFACEMETHODIMP GetToolTip(IShellItemArray*, LPWSTR* ppszInfotip)
    {
        if (ppszInfotip) *ppszInfotip = NULL;
        return S_OK;
    }

    IFACEMETHODIMP GetState(IShellItemArray*, BOOL, EXPCMDSTATE* pCmdState)
    {
        if (!pCmdState) return E_POINTER;
        *pCmdState = ECS_ENABLED;
        return S_OK;
    }

    IFACEMETHODIMP Invoke(IShellItemArray*, IBindCtx*)
    {
        // Parent has sub-commands; Invoke should not be called.
        return E_NOTIMPL;
    }

    IFACEMETHODIMP GetFlags(EXPCMDFLAGS* pFlags)
    {
        if (!pFlags) return E_POINTER;
        *pFlags = ECF_HASSUBCOMMANDS;
        LogMsg("Parent GetFlags -> ECF_HASSUBCOMMANDS");
        return S_OK;
    }

    IFACEMETHODIMP EnumSubCommands(IEnumExplorerCommand** ppEnum)
    {
        LogMsg("Parent EnumSubCommands called");
        if (!ppEnum) return E_POINTER;
        *ppEnum = NULL;
        CEnumCommands* e = new CEnumCommands();
        if (!e) return E_OUTOFMEMORY;
        HRESULT hr = e->QueryInterface(IID_PPV_ARGS(ppEnum));
        e->Release();
        return hr;
    }
};

// ── Class factory (creates either parent or child) ───────────────────────
class CClassFactory : public IClassFactory
{
    LONG m_ref;
    const ToolConfig* m_cfg;  // NULL = parent
public:
    CClassFactory(const ToolConfig* cfg) : m_ref(1), m_cfg(cfg) { }

    IFACEMETHODIMP QueryInterface(REFIID riid, void** ppv)
    {
        if (!ppv) return E_POINTER;
        *ppv = NULL;
        if (IsEqualIID(riid, IID_IUnknown) || IsEqualIID(riid, IID_IClassFactory))
            *ppv = static_cast<IClassFactory*>(this);
        else
            return E_NOINTERFACE;
        AddRef();
        return S_OK;
    }
    IFACEMETHODIMP_(ULONG) AddRef()  { return InterlockedIncrement(&m_ref); }
    IFACEMETHODIMP_(ULONG) Release()
    {
        LONG c = InterlockedDecrement(&m_ref);
        if (c == 0) delete this;
        return c;
    }

    IFACEMETHODIMP CreateInstance(IUnknown* pUnkOuter, REFIID riid, void** ppv)
    {
        LogMsg("CClassFactory::CreateInstance (cfg=%p)", m_cfg);
        if (pUnkOuter) return CLASS_E_NOAGGREGATION;
        if (m_cfg == NULL) {
            CParentCommand* cmd = new CParentCommand();
            if (!cmd) return E_OUTOFMEMORY;
            HRESULT hr = cmd->QueryInterface(riid, ppv);
            cmd->Release();
            return hr;
        } else {
            CChildCommand* cmd = new CChildCommand(m_cfg);
            if (!cmd) return E_OUTOFMEMORY;
            HRESULT hr = cmd->QueryInterface(riid, ppv);
            cmd->Release();
            return hr;
        }
    }

    IFACEMETHODIMP LockServer(BOOL fLock)
    {
        if (fLock) InterlockedIncrement(&g_dllRef);
        else InterlockedDecrement(&g_dllRef);
        return S_OK;
    }
};

// ── DLL exports ─────────────────────────────────────────────────────────
STDAPI DllGetClassObject(REFCLSID rclsid, REFIID riid, void** ppv)
{
    LogGuid("DllGetClassObject rclsid", rclsid);
    if (!ppv) return E_POINTER;
    *ppv = NULL;

    // Parent command first
    if (IsEqualCLSID(rclsid, PARENT_CLSID)) {
        LogMsg("DllGetClassObject: matched PARENT");
        CClassFactory* pcf = new CClassFactory(NULL);
        if (!pcf) return E_OUTOFMEMORY;
        HRESULT hr = pcf->QueryInterface(riid, ppv);
        pcf->Release();
        return hr;
    }

    // Child commands
    for (int i = 0; i < TOOL_COUNT; i++) {
        if (IsEqualCLSID(rclsid, g_toolConfigs[i].clsid)) {
            LogMsg("DllGetClassObject: matched tool #%d", i);
            CClassFactory* pcf = new CClassFactory(&g_toolConfigs[i]);
            if (!pcf) return E_OUTOFMEMORY;
            HRESULT hr = pcf->QueryInterface(riid, ppv);
            pcf->Release();
            return hr;
        }
    }
    LogMsg("DllGetClassObject: CLASS_E_CLASSNOTAVAILABLE");
    return CLASS_E_CLASSNOTAVAILABLE;
}

STDAPI DllCanUnloadNow(void)
{
    return g_dllRef == 0 ? S_OK : S_FALSE;
}

BOOL WINAPI DllMain(HINSTANCE hinst, DWORD reason, LPVOID)
{
    if (reason == DLL_PROCESS_ATTACH) {
        LogMsg("=== DLL loaded (DllMain) ===");
        DisableThreadLibraryCalls(hinst);
    } else if (reason == DLL_PROCESS_DETACH) {
        LogMsg("=== DLL unloaded ===");
    }
    return TRUE;
}
